# Generated by Django 4.1.3 on 2022-11-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('wholeText', models.TextField()),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordOriginal', models.CharField(max_length=128)),
                ('wordTranslate', models.CharField(max_length=128)),
                ('wordDescription', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goen.book')),
            ],
            options={
                'db_table': 'words',
            },
        ),
        migrations.CreateModel(
            name='WordLearned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('nextDayLearn', models.DateField(auto_now_add=True)),
                ('is_learned', models.BooleanField(default=False)),
                ('learnPerson', models.CharField(max_length=128)),
                ('learnWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goen.word')),
            ],
            options={
                'db_table': 'wordLearned',
            },
        ),
    ]
