# Generated by Django 4.1.3 on 2022-12-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/%Y/%m/%d/'),
        ),
    ]
