# Generated by Django 4.1.3 on 2022-12-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goen', '0003_rename_book_story_alter_story_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='book',
            new_name='story',
        ),
    ]
