# Generated by Django 4.1.3 on 2022-12-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goen', '0004_rename_book_word_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='uploadDate',
            new_name='upload_date',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='wholeText',
            new_name='whole_text',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='wordDescription',
            new_name='word_description',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='wordOriginal',
            new_name='word_original',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='wordTranslate',
            new_name='word_translate',
        ),
        migrations.RenameField(
            model_name='wordlearned',
            old_name='learnPerson',
            new_name='learn_person',
        ),
        migrations.RenameField(
            model_name='wordlearned',
            old_name='learnWord',
            new_name='learn_word',
        ),
        migrations.RenameField(
            model_name='wordlearned',
            old_name='nextDayLearn',
            new_name='next_day_learn',
        ),
    ]
