# Generated by Django 4.1.3 on 2022-12-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goen', '0005_rename_uploaddate_story_upload_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlearned',
            old_name='count',
            new_name='progress',
        ),
    ]
