# Generated by Django 4.1.3 on 2023-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goen', '0006_rename_count_wordlearned_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlearned',
            name='to_repeat',
            field=models.BooleanField(default=False),
        ),
    ]
